language: java
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk:
  - oraclejdk8
  - openjdk7
  - openjdk6
 
stages:
  - test
  - name: deploySnapshot
    if: branch = master
  - name: deployRelease
    if: tag IS present
    
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
      
install: mvn --settings .travis/settings.xml install -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
script: skip

jobs:
  include:
    - stage: deploySnapshot
      addons: skip
      install: skip
      script: skip
      deploy:
        provider: script
        script: .travis/deploy.sh
        skip_cleanup: true
        on:
          repo: Hi-Fi/robotframework-httprequestlibrary
          branch: master
          jdk: oraclejdk8
    - stage: deployRelease
      addons: skip
      install: skip
      script: skip
      deploy:
        provider: script
        script: .travis/deploy.sh
        skip_cleanup: true
        on:
          repo: Hi-Fi/robotframework-httprequestlibrary
          tags: true
          jdk: oraclejdk8